name: VTU Internship Watcher

on:
  schedule:
    - cron: "*/30 * * * *" # Every 30 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run VTU Watcher script
        run: python main.py

      - name: Commit updated seen.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add seen.json
          git commit -m "Update seen.json" || echo "No changes to commit"
          git push
