name: VTU Internship Watcher

on:
  schedule:
    - cron: "0 0 * * *"  # runs once per day at midnight UTC
  workflow_dispatch:

jobs:
  run-watcher:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_TO:  ${{ secrets.EMAIL_TO }}
          DEBUG: "1"
        run: |
          python watcher.py
